
plotString={'CorretAll', 'ErrorAll', 'NoResponseAll','CorrectLeft', 'ErrorLeft','NoResponseLeft', 'CorrectRight', 'ErrorRight','NoResponseRight', 'UnexpectedRewardAll', 'RewardOmissionAll', 'UnexpectedRewardLeft',...
    'RewardOmissionLeft','UnexpectedRewardRight','RewardOmissionRight','RewardOmissionRightError', 'RewardOmissionRightCorrect', 'RewardOmissionLeftError','RewardOmissionLeftCorrect',...
    'PhotoStimLeftAll','PhotoStimRightAll','PhotoStimCorrectLeft','PhotoStimErrorLeft','PhotoStimNoresponseLeft','PhotoStimCorrectRight','PhotoStimErrorRight','PhotoStimNoresponseRight', ...
    'PhotoStimSampleLeftAll', 'PhotoStimSampleCorrectLeft' , 'PhotoStimSampleErrorLeft', 'PhotoStimSampleNoresponseLeft','PhotoStimSampleRightAll', 'PhotoStimSampleCorrectRight' , 'PhotoStimSampleErrorRight', 'PhotoStimSampleNoresponseRight', ...
    'PhotoStimDelayLeftAll', 'PhotoStimDelayCorrectLeft' , 'PhotoStimDelayErrorLeft', 'PhotoStimDelayNoresponseLeft','PhotoStimDelayRightAll', 'PhotoStimDelayCorrectRight' , 'PhotoStimDelayErrorRight', 'PhotoStimDelayNoresponseRight', ...
    'NoStimLeft','NoStimRight', ...
    'Weak1','Weak2','Strong1','Strong2','Weak1Correct','Weak1Wrong','Weak2Correct','Weak2Wrong','Strong1Correct','Strong1Wrong','Strong2Correct','Strong2Wrong', ...
    'Weak1DelayInhibition','Weak2DelayInhibition','Strong1DelayInhibition','Strong2DelayInhibition','Weak1CorrectDelayInhibition','Weak1WrongDelayInhibition','Weak2CorrectDelayInhibition','Weak2WrongDelayInhibition','Strong1CorrectDelayInhibition','Strong1WrongDelayInhibition','Strong2CorrectDelayInhibition','Strong2WrongDelayInhibition', ...
    'PhotoStimResponseLeftAll', 'PhotoStimResponseCorrectLeft' , 'PhotoStimResponseErrorLeft', 'PhotoStimResponseNoresponseLeft','PhotoStimResponseRightAll', 'PhotoStimResponseCorrectRight' , 'PhotoStimResponseErrorRight', 'PhotoStimResponseNoresponseRight', ...
    'DelayLeftALMInhibition_LeftTrial', 'DelayLeftALMInhibition_RightTrial','DelayRightALMInhibition_LeftTrial','DelayRightALMInhibition_RightTrial', ...
    'DelayLeftALMInhibition_LeftTrial_C', 'DelayLeftALMInhibition_RightTrial_C','DelayRightALMInhibition_LeftTrial_C','DelayRightALMInhibition_RightTrial_C', ...
    'DelayLeftALMInhibition_LeftTrial_E', 'DelayLeftALMInhibition_RightTrial_E','DelayRightALMInhibition_LeftTrial_E','DelayRightALMInhibition_RightTrial_E', ...
    'SampleLeftALMInhibition_LeftTrial', 'SampleLeftALMInhibition_RightTrial','SampleRightALMInhibition_LeftTrial','SampleRightALMInhibition_RightTrial', ...
    'SampleLeftALMInhibition_LeftTrial_C', 'SampleLeftALMInhibition_RightTrial_C','SampleRightALMInhibition_LeftTrial_C','SampleRightALMInhibition_RightTrial_C', ...
    'SampleLeftALMInhibition_LeftTrial_E', 'SampleLeftALMInhibition_RightTrial_E','SampleRightALMInhibition_LeftTrial_E','SampleRightALMInhibition_RightTrial_E', ...   
    'LJNormal', 'LJInhibition1', 'LJInhibition2','LJInhibition3','LaserPower1S','LaserPower2S','LaserPower3S','LaserPower4S','LaserPower1D','LaserPower2D','LaserPower3D','LaserPower4D','GoLeftNoStimCorrect','GoRightNoStimCorrect','NoGoLeftNoStimCorrect','NoGoRightNoStimCorrect','GoLeftNoStimError','GoRightNoStimError','NoGoLeftNoStimError','NoGoRightNoStimError','GoAllNoStimNoResponse'};
    


 
% for multisense
plotMatrix=[   0,        0,           0,           0,           0,         0,             0,            0,            0,                 0,              0,                 0,...
               0,             0,                       0,                0,                      0,                              0,                      0,...
               0,             0,               0,                       0,                    0,                    0,                     0,                      0 ,...
               1                        0                           0                                0                           1                                0                        0                             0,...
               1                     0                                  0                      0                            1                         0                                      0                         0 ...
               0      0 ...
               0  0    0          0           1             0             1            0               1               0              1               0        ...
               0  0    0          0           0             0             0            0               0               0              0               0        ...
               0                     0                                  0                      0                            0                         0                                      0                         0  ...
               1     1    1   1 ...
               1     1    1   1 ...
               1     1    1   1 ...
               1     1    1   1 ...
               1     1    1   1 ...
               1     1    1   1 ...
               0    0  0  0 ...
               1 1 1 1 1 1 1 1 ...
               1 1 1 1 1 1 1 1 1];
            

           
% save matrix defines which data to save/compute  
% for other probe
% saveMatrix=[   0,        0,           0,           1,           1,         1,             1,            1,            1,                 0,              0,                 0,...
%                0,             0,                       0,                0,                      0,                              0,                      0,...
%                0,             0,               0,                       0,                    0,                    0,                     0,                      0 ,...
%                1                        1                           1                                1                           1                                1                        1                             1,...
%                1                     1                                  1                      1                            1                         1                                      1                         1 ...
%                1      1 ...
%                0  0    0          0           0             0             0            0               0               0              0               0        ...
%                0  0    0          0           0             0             0            0               0               0              0               0      ...
%                1                     1                                  1                      1                            1                         1                                      1                         1  ...
%                0    0    0   0 ...
%                0    0    0   0 ...
%                0    0    0   0 ...
%                0    0    0   0 ...
%                0    0    0   0 ...
%                0    0    0   0 ...
%                0    0    0   0];

% for neuropixel probe
saveMatrix=[   0,        0,           0,           1,           1,         1,             1,            1,            1,                 0,              0,                 0,...
               0,             0,                       0,                0,                      0,                              0,                      0,...
               0,             0,               0,                       0,                    0,                    0,                     0,                      0 ,...
               1                        1                           1                                1                           1                                1                        1                             1,...
               1                     1                                  1                      1                            1                         1                                      1                         1 ...
               1      1 ...
               0  0    0          0           0             0             0            0               0               0              0               0        ...
               0  0    0          0           0             0             0            0               0               0              0               0      ...
               0                     0                                  0                      0                            0                         0                                      0                         0  ...
               0    0    0   0 ...
               0    0    0   0 ...
               0    0    0   0 ...
               0    0    0   0 ...
               0    0    0   0 ...
               0    0    0   0 ...
               0    0    0   0 ...
               1    1    1   1 1 1 1 1 ...
               1 1 1 1 1 1 1 1 1];

           
           
%            saveMatrix=[   0,        0,           0,           1,           1,         1,             1,            1,            1,                 0,              0,                 0,...
%                0,             0,                       0,                0,                      0,                              0,                      0,...
%                0,             0,               0,                       0,                    0,                    0,                     0,                      0 ,...
%                0                        0                           0                                0                           0                                0                        0                             0,...
%                0                     0                                  0                      0                            0                         0                                      0                         0 ...
%                1      1 ...
%                0  0    0          0           0             0             0            0               0               0              0               0        ...
%                0  0    0          0           0             0             0            0               0               0              0               0      ...
%                0                     0                                  0                      0                            0                         0                                      0                         0  ...
%                1    1    1   1 ...
%                1    1    1   1 ...
%                1    1    1   1 ...
%                1    1    1   1 ...
%                1    1    1   1 ...
%                1    1    1   1 ...
%                0    0    0   0];
